/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_game_ad_gameADCon */

#ifndef _Included_com_game_ad_gameADCon
#define _Included_com_game_ad_gameADCon
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_game_ad_gameADCon
 * Method:    dmOfferWallAddListStateCallBack
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_game_ad_gameADCon_dmOfferWallAddListStateCallBack
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_game_ad_gameADCon
 * Method:    dmOfferWallCacheVideoStateCallBack
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_game_ad_gameADCon_dmOfferWallCacheVideoStateCallBack
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_game_ad_gameADCon
 * Method:    dmOfferWallPlayVideoStateCallBack
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_game_ad_gameADCon_dmOfferWallPlayVideoStateCallBack
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_game_ad_gameADCon
 * Method:    dmOfferWallCheckPointsStateCallBack
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_game_ad_gameADCon_dmOfferWallCheckPointsStateCallBack
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_game_ad_gameADCon
 * Method:    dmOfferWallConsumePointStateCallBack
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_game_ad_gameADCon_dmOfferWallConsumePointStateCallBack
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_game_ad_gameADCon
 * Method:    dmInterADLoadResulta
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_game_ad_gameADCon_dmInterADLoadResulta
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
