/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_game_ad_gameADCon */

#ifndef _Included_com_game_ad_gameADCon
#define _Included_com_game_ad_gameADCon
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_game_ad_gameADCon
 * Method:    dmOfferWallAddListStateCallBack
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_game_ad_gameADCon_dmOfferWallAddListStateCallBack
  (JNIEnv * env, jclass tmpClass, jint value);

/*
 * Class:     com_game_ad_gameADCon
 * Method:    dmOfferWallCacheVideoStateCallBack
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_game_ad_gameADCon_dmOfferWallCacheVideoStateCallBack
  (JNIEnv * env, jclass tmpClass, jint value);

/*
 * Class:     com_game_ad_gameADCon
 * Method:    dmOfferWallPlayVideoStateCallBack
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_game_ad_gameADCon_dmOfferWallPlayVideoStateCallBack
  (JNIEnv * env, jclass tmpClass, jint value);

/*
 * Class:     com_game_ad_gameADCon
 * Method:    dmOfferWallCheckPointsStateCallBack
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_game_ad_gameADCon_dmOfferWallCheckPointsStateCallBack
  (JNIEnv * env, jclass tmpClass, jint value, jint value2);

/*
 * Class:     com_game_ad_gameADCon
 * Method:    dmOfferWallConsumePointStateCallBack
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_game_ad_gameADCon_dmOfferWallConsumePointStateCallBack
  (JNIEnv * env, jclass tmpClass, jint value, jint value2);

/*
 * Class:     com_game_ad_gameADCon
 * Method:    dmInterADLoadResulta
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_game_ad_gameADCon_dmInterADLoadResulta
  (JNIEnv * env, jclass tmpClass, jint value);

#ifdef __cplusplus
}
#endif

extern void gameLoadDMOfferWallList();
extern void gameLoadDMOfferWallVideo();
extern void gameLoadDMOfferWallConsumeTotal();
extern void gameSetDMOfferConsume(int consumePoint);
extern void gameLoadDMInterAD();
extern void gameShowDMInterAD();
#endif
