//
//  GameMusicKey.h
//  CaratonFatans
//
//  Created by jack on 13-12-20.
//
//

#ifndef CaratonFatans_GameMusicKey_h
#define CaratonFatans_GameMusicKey_h


typedef enum {

    GAME_MUSIC_EFFECT_TYPE_NONE,
    GAME_MUSIC_EFFECT_TYPE_MAIN_COMPLISH,
    GAME_MUSIC_EFFECT_TYPE_MAIN_BG_MUSIC,
    GAME_MUSIC_EFFECT_TYPE_MAIN_SELECT,
    GAME_MUSIC_EFFECT_TYPE_MAIN_UNLOCK,
    
    GAME_MUSIC_EFFECT_TYPE_ITEM_MENU_SELECT,
    GAME_MUSIC_EFFECT_TYPE_ITEM_COUNT_DOWN,
    GAME_MUSIC_EFFECT_TYPE_ITEM_GO,
    GAME_MUSIC_EFFECT_TYPE_ITEM_TOWER_SELECT,
    GAME_MUSIC_EFFECT_TYPE_ITEM_BOMB,
    GAME_MUSIC_EFFECT_TYPE_ITEM_TOWER_UPDATE,
    GAME_MUSIC_EFFECT_TYPE_ITEM_GAME_LOSE,
    GAME_MUSIC_EFFECT_TYPE_ITEM_GAME_WIN,
    
    
    GAME_MUSIC_EFFECT_TYPE_MAX,
}GAME_MUSIC_EFFECT_TYPE;


#endif
